function [outcomes,...
    outcomeString]          = estimateGnBStaticOutcomes(accelData,...
                                rotData, fs, isAndroid)

accelMLxAPxVert             = preprocessGnBStaticStream(accelData,...
                                rotData, fs, isAndroid);

%% Compute outputs
[steadinessML,...
    steadinessAP,...
    steadinessR]            = computeSteadiness(accelMLxAPxVert);

outcomes                    = [steadinessML, steadinessAP, steadinessR];
outcomeString               = sprintf(strcat(...
    'Steadiness ML:  %0.16f -ln[m/sec/sec]\n',...
    'Steadiness AP:  %0.16f -ln[m/sec/sec]\n',...
    'Steadiness R:  %0.16f -ln[m/sec/sec]\n'...
    ),...
    outcomes);
end