function kotlinStr      = printGnBStaticOutcomesAsKotlin(outcomes)

kotlinStr               = sprintf(strcat('GnBStaticOutcomes(\n',...
                            'stabilityR = %0.16f,\n',...
                            'stabilityML = %0.16f,\n',...
                            'stabilityAP = %0.16f,\n',...
                            ')'),...
                            outcomes);

if nargout < 1
    disp(kotlinStr)
end
end